# This is a GitHub Actions workflow file for deploying a static site to DigitalOcean using SSH and rsync.
name: Deploy to DigitalOcean
on:
  push:
    branches: [main] # Adjust this to your main branch name

env:
  SITE_URL: 'https://hypnagaga.com'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24' # Adjust based on your needs
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to DigitalOcean
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=yes -o BatchMode=yes" -avz --delete ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/hypnagaga.com/html/